# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 683658ab941662e97ee5527e6c1d096ba79d4dbc960964f34e38845eeea4228bfa8fa34a22a2034aa2f3d22b576c552f6cdd0c6557f0d804c2f1c49fd86940a7

test:
  secret_key_base: 6f9a004d57b72e6f5fbb654ad30389b75588f6cc4580469b578261b26aef586cc3c187b98a0b12ffe6752b5c6f0e241eff80aaaa7da64f347047fcdb1f6c4981

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
